# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hello_unary.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'hello_unary.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11hello_unary.proto\"\x14\n\x04User\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x19\n\x05Hello\x12\x10\n\x08greeting\x18\x01 \x01(\t2.\n\x0cHelloService\x12\x1e\n\x0bhello_world\x12\x05.User\x1a\x06.Hello\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hello_unary_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=21
  _globals['_USER']._serialized_end=41
  _globals['_HELLO']._serialized_start=43
  _globals['_HELLO']._serialized_end=68
  _globals['_HELLOSERVICE']._serialized_start=70
  _globals['_HELLOSERVICE']._serialized_end=116
# @@protoc_insertion_point(module_scope)
